name: Count Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Count files
        run: |
          find . -type f | wc -l > file_count.txt

      - name: Upload file_count.txt
        uses: actions/upload-artifact@v3
        with:
          name: file_count.txt
          path: file_count.txt
