name: Generate Filetree with Row Number

on:
  push:
    branches: main

jobs:
  generate-filetree:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Generate filetree
        run: |
          awk '{ print NR, $0 }' < <(find . -type f) > filetree.txt

      - name: Upload filetree
        uses: actions/upload-artifact@v3
        with:
          name: filetree.txt
          path: filetree.txt